/* The following code was generated by JFlex 1.4.3 on 11/12/16 22:29 */

/* --------------------------Codigo de Usuario----------------------- */
package analizadorLex;

import java_cup.runtime.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/12/16 22:29 from the specification file
 * <tt>C:/Users/abdel/workspace/pecl/alexico.lex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\2\1\0\1\3\1\1\22\0\1\3\7\0\1\42"+
    "\1\43\1\40\1\36\1\44\1\37\1\0\1\41\12\5\1\32\1\45"+
    "\1\34\1\33\1\35\2\0\32\4\6\0\1\12\1\16\1\4\1\21"+
    "\1\17\1\30\1\11\1\27\1\14\1\4\1\26\1\24\1\13\1\20"+
    "\1\10\1\6\1\4\1\7\1\15\1\23\1\31\1\22\1\25\3\4"+
    "\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\16\3\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\2\3\1\21\1\3\1\22\1\3\1\23"+
    "\6\3\1\24\6\3\1\25\1\26\1\27\1\30\2\3"+
    "\1\31\4\3\1\32\1\3\1\33\1\34\6\3\1\35"+
    "\1\3\1\36\2\3\1\37\1\40\1\41\6\3\1\42"+
    "\1\43\1\44\1\45\3\3\1\46\1\47\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\46\0\114\0\46\0\162\0\230\0\276\0\344"+
    "\0\u010a\0\u0130\0\u0156\0\u017c\0\u01a2\0\u01c8\0\u01ee\0\u0214"+
    "\0\u023a\0\u0260\0\u0286\0\u02ac\0\u02d2\0\46\0\u02f8\0\u031e"+
    "\0\46\0\46\0\46\0\46\0\46\0\46\0\46\0\46"+
    "\0\u0344\0\u036a\0\162\0\u0390\0\162\0\u03b6\0\162\0\u03dc"+
    "\0\u0402\0\u0428\0\u044e\0\u0474\0\u049a\0\162\0\u04c0\0\u04e6"+
    "\0\u050c\0\u0532\0\u0558\0\u057e\0\46\0\46\0\46\0\46"+
    "\0\u05a4\0\u05ca\0\162\0\u05f0\0\u0616\0\u063c\0\u0662\0\162"+
    "\0\u0688\0\162\0\162\0\u06ae\0\u06d4\0\u06fa\0\u0720\0\u0746"+
    "\0\u076c\0\162\0\u0792\0\162\0\u07b8\0\u07de\0\162\0\162"+
    "\0\162\0\u0804\0\u082a\0\u0850\0\u0876\0\u089c\0\u08c2\0\162"+
    "\0\162\0\162\0\162\0\u08e8\0\u090e\0\u0934\0\162\0\162"+
    "\0\162";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\5\1\12\1\5\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\5\1\23\2\5\1\24\1\5"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\50\0\1\4\47\0\26\5"+
    "\21\0\1\6\44\0\3\5\1\41\22\5\20\0\13\5"+
    "\1\42\12\5\20\0\3\5\1\43\22\5\20\0\14\5"+
    "\1\44\11\5\20\0\11\5\1\45\2\5\1\46\7\5"+
    "\1\47\1\5\20\0\22\5\1\50\3\5\20\0\4\5"+
    "\1\51\6\5\1\52\12\5\20\0\14\5\1\53\3\5"+
    "\1\54\5\5\20\0\4\5\1\55\21\5\20\0\4\5"+
    "\1\56\21\5\20\0\6\5\1\57\17\5\20\0\3\5"+
    "\1\60\17\5\1\61\2\5\20\0\3\5\1\62\17\5"+
    "\1\63\2\5\20\0\6\5\1\64\17\5\47\0\1\65"+
    "\45\0\1\66\1\0\1\67\43\0\1\70\16\0\4\5"+
    "\1\71\21\5\20\0\6\5\1\72\17\5\20\0\15\5"+
    "\1\73\10\5\20\0\17\5\1\74\6\5\20\0\10\5"+
    "\1\75\15\5\20\0\4\5\1\76\21\5\20\0\5\5"+
    "\1\77\20\5\20\0\15\5\1\100\10\5\20\0\11\5"+
    "\1\101\14\5\20\0\17\5\1\102\6\5\20\0\3\5"+
    "\1\103\22\5\20\0\25\5\1\104\20\0\13\5\1\105"+
    "\12\5\20\0\10\5\1\106\15\5\20\0\10\5\1\107"+
    "\15\5\20\0\20\5\1\110\5\5\20\0\5\5\1\111"+
    "\20\5\20\0\15\5\1\112\10\5\20\0\13\5\1\113"+
    "\12\5\20\0\2\5\1\114\23\5\20\0\20\5\1\115"+
    "\5\5\20\0\10\5\1\116\15\5\20\0\13\5\1\117"+
    "\12\5\20\0\13\5\1\120\12\5\20\0\14\5\1\121"+
    "\11\5\20\0\17\5\1\122\6\5\20\0\20\5\1\123"+
    "\5\5\20\0\11\5\1\124\14\5\20\0\3\5\1\125"+
    "\22\5\20\0\5\5\1\126\20\5\20\0\13\5\1\127"+
    "\12\5\20\0\14\5\1\130\11\5\20\0\13\5\1\131"+
    "\12\5\20\0\13\5\1\132\12\5\20\0\13\5\1\133"+
    "\12\5\20\0\6\5\1\134\17\5\20\0\13\5\1\135"+
    "\12\5\20\0\6\5\1\136\17\5\20\0\7\5\1\137"+
    "\16\5\20\0\3\5\1\140\22\5\20\0\14\5\1\141"+
    "\11\5\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2394];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\21\1\1\11\2\1\10\11"+
    "\24\1\4\11\51\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[97];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    /*  Generamos un java_cup.Symbol para guardar el tipo de token encontrado */
    private Symbol Symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado junto con su valor */
    private Symbol Symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }
    
    /* Generamos una lista de Simbolos utilizados */
    
    private TablaSimbolos st = new TablaSimbolos(); 
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 102) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	System.out.println(st.imprimirListaSimbolos());
	st.imprimirListaErroresLexicos();
  yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 23: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"distinto",yyline,yycolumn)); 
		return Symbol(sym.DISTINTO);
          }
        case 41: break;
        case 15: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"coma",yyline,yycolumn)); 
		return Symbol(sym.COMA);
          }
        case 42: break;
        case 28: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"var",yyline,yycolumn)); 
		return Symbol(sym.VAR);
          }
        case 43: break;
        case 16: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"punto_coma",yyline,yycolumn)); 
		return Symbol(sym.PUNTO_COMA);
          }
        case 44: break;
        case 21: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"asignacion",yyline,yycolumn)); 
		return Symbol(sym.ASIGNACION);
          }
        case 45: break;
        case 9: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"suma",yyline,yycolumn)); 
		return Symbol(sym.SUMA);
          }
        case 46: break;
        case 8: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"mayor",yyline,yycolumn)); 
		return Symbol(sym.MAYOR);
          }
        case 47: break;
        case 24: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"mayor_igual",yyline,yycolumn)); 
		return Symbol(sym.MAYOR_IGUAL);
          }
        case 48: break;
        case 30: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"skip",yyline,yycolumn)); 
		return Symbol(sym.SKIP);
          }
        case 49: break;
        case 13: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"parentesis_abierto",yyline,yycolumn)); 
		return Symbol(sym.PARENTESIS_ABIERTO);
          }
        case 50: break;
        case 39: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"integer",yyline,yycolumn)); 
		return Symbol(sym.INTEGER);
          }
        case 51: break;
        case 3: 
          { st.getListaSimpolos().add(new Simbolo("ide("+yytext()+")","ide",yyline,yycolumn)); 
		return Symbol(sym.IDE, new String("ide("+yytext()+")"));
          }
        case 52: break;
        case 33: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"then",yyline,yycolumn)); 
		return Symbol(sym.THEN);
          }
        case 53: break;
        case 27: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"not",yyline,yycolumn)); 
		return Symbol(sym.NOT);
          }
        case 54: break;
        case 17: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"or",yyline,yycolumn)); 
		return Symbol(sym.OR);
          }
        case 55: break;
        case 40: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"boolean",yyline,yycolumn)); 
		return Symbol(sym.BOOLEAN);
          }
        case 56: break;
        case 14: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"parentesis_cerrado",yyline,yycolumn)); 
		return Symbol(sym.PARENTESIS_CERRADO);
          }
        case 57: break;
        case 34: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"begin",yyline,yycolumn)); 
		return Symbol(sym.BEGIN);
          }
        case 58: break;
        case 35: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"write",yyline,yycolumn)); 
		return Symbol(sym.WRITE);
          }
        case 59: break;
        case 36: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"while",yyline,yycolumn)); 
		return Symbol(sym.WHILE);
          }
        case 60: break;
        case 10: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"resta",yyline,yycolumn)); 
		return Symbol(sym.RESTA);
          }
        case 61: break;
        case 38: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"program",yyline,yycolumn)); 
		return Symbol(sym.PROGRAM);
          }
        case 62: break;
        case 37: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"false",yyline,yycolumn)); 
		return Symbol(sym.FALSE);
          }
        case 63: break;
        case 19: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"if",yyline,yycolumn)); 
		return Symbol(sym.IF);
          }
        case 64: break;
        case 29: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"read",yyline,yycolumn)); 
		return Symbol(sym.READ);
          }
        case 65: break;
        case 6: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"igual",yyline,yycolumn)); 
		return Symbol(sym.IGUAL);
          }
        case 66: break;
        case 32: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"true",yyline,yycolumn)); 
		return Symbol(sym.TRUE);
          }
        case 67: break;
        case 25: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"and",yyline,yycolumn)); 
		return Symbol(sym.AND);
          }
        case 68: break;
        case 20: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"do",yyline,yycolumn)); 
		return Symbol(sym.DO);
          }
        case 69: break;
        case 12: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"division",yyline,yycolumn)); 
		return Symbol(sym.DIVISION);
          }
        case 70: break;
        case 1: 
          { st.getListaErroresLexicos().add("Caracter ilegal en la linea "+(yyline+1)+" y columna "+(yycolumn+1)+": <"+yytext()+">");
          }
        case 71: break;
        case 5: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"dos_puntos",yyline,yycolumn)); 
		return Symbol(sym.DOS_PUNTOS);
          }
        case 72: break;
        case 4: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"num("+yytext()+")",yyline,yycolumn)); 
		return Symbol(sym.ENTERO, new Integer(yytext()));
          }
        case 73: break;
        case 18: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"is",yyline,yycolumn)); 
		return Symbol(sym.IS);
          }
        case 74: break;
        case 11: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"multiplicacion",yyline,yycolumn)); 
		return Symbol(sym.MULTIPLICACION);
          }
        case 75: break;
        case 22: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"menor_igual",yyline,yycolumn)); 
		return Symbol(sym.MENOR_IGUAL);
          }
        case 76: break;
        case 26: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"end",yyline,yycolumn)); 
		return Symbol(sym.END);
          }
        case 77: break;
        case 31: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"else",yyline,yycolumn)); 
		return Symbol(sym.ELSE);
          }
        case 78: break;
        case 7: 
          { st.getListaSimpolos().add(new Simbolo(yytext(),"menor",yyline,yycolumn)); 
		return Symbol(sym.MENOR);
          }
        case 79: break;
        case 2: 
          { 
          }
        case 80: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
